### ISSUE TITLE
Do I need to transform the image to model input size? And how to add mosaic on the original image?

### ISSUE THREAD

**Issue by magic3584** [tucan9389/ObjectSegmentation-CoreML#18]
Hi, sorry the this issue to ask for help.

I have followed the demo.
<img width="342" alt="Screenshot 2023-11-03 at 10 39 30" src="https://github.com/tucan9389/SemanticSegmentation-CoreML/assets/6275110/5070d9d9-1099-4d42-9fd9-1b4fa47abaa1">

The input image is 1920 * 1080 pixel, and the result is 513 * 513 array, renderView is 300 * 300 pt.

Why the renderView is rendered normal even the input is not suitable?
And how can I add mosaic on the original image depend on the segmentation?

**Comment by tucan9389** [comment]
Hello @magic3584,

Could you give me more about `renderedView`? If you refer to [`DrawingSegmentationView`](https://github.com/tucan9389/SemanticSegmentation-CoreML/blob/master/SemanticSegmentation-CoreML/DrawingSegmentationView.swift), there is resizing algorithm in the `DrawingSegmentationView`. 

And I don't follow `add mosaic`. Could you elaborate more about this? If you give some example image, it would also be great to understand :)

**Comment by magic3584** [comment]
Thanks for the response @tucan9389 

Yes, the renderView is **DrawingSegmentationView**. 
I wanna use DeepLabV3.mlmodel (https://developer.apple.com/machine-learning/models/) to reach the goal like left corner image, which is accomplished by using Apple API **VNGeneratePersonSegmentationRequest**.

I have accomplished like
<img width="342" src="https://github.com/tucan9389/SemanticSegmentation-CoreML/assets/6275110/072156ec-2c12-44ef-9d1c-91cba259d059">

As u can see the background is not clear. Perhaps because the original image is 1920 * 1080 and  the output of DeepLabV3 is 513 * 513. 

Is there any way to make the background clear like [LiveFaceDetectionAndFaceParsingViewController](https://github.com/tucan9389/SemanticSegmentation-CoreML/blob/master/SemanticSegmentation-CoreML/LiveFaceDetectionAndFaceParsingViewController.swift)? 

**Mosaic** is a style like 
<img width="342" src="https://imgv3.fotor.com/images/side/MakeYourImageintoArtwiththeMosaicEffect.jpg">
