### ISSUE TITLE
The result is rotated

### ISSUE THREAD

**Issue by DanielZanchi** [tucan9389/ObjectSegmentation-CoreML#3]
Hello, 
the project is very interesting but it's not working:

<img src="https://user-images.githubusercontent.com/6886116/66909082-7255a500-f00c-11e9-98d5-54da7d34c457.png" width=240px>

Any idea why?

Daniel

**Comment by tucan9389** [comment]
@DanielZanchi 

Oh, the result is rotated. I think it's a simple issue. I'll check when I have time.

**Comment by tucan9389** [comment]
@DanielZanchi 

Please check the last commit. I fixed it.

<img src="https://user-images.githubusercontent.com/37643248/67212742-c1119d80-f457-11e9-9081-077f1bf70dc4.png" width=320px>
