### ISSUE TITLE
Extract Image 

### ISSUE THREAD

**Issue by ismailismail** [tucan9389/ObjectSegmentation-CoreML#4]
is there any way to extract image from segmentation map or how to convert  MLMultiArray to image?

**Comment by tucan9389** [comment]
I haven't implemented yet, but you can save the image file with the following step.

1. draw on `UIView` with `MLMultiArray` (like [my implement](https://github.com/tucan9389/ObjectSegmentation-CoreML/blob/master/ObjectSegmentation-CoreML/DrawingSegmentationView.swift)) 
2. save the `UIView` as an image (https://stackoverflow.com/a/17145149/4160632)

If you have any questions, please tell me.

**Comment by ismailismail** [comment]
thanks for fast response 
I attached two image that shows your step. I want to cut the cat on the image. is it possible?
![Screenshot 2019-11-26 13 32 35](https://user-images.githubusercontent.com/451978/69622113-615b7300-1051-11ea-9f49-32a032722071.png)
![Screenshot 2019-11-26 13 32 41](https://user-images.githubusercontent.com/451978/69622114-615b7300-1051-11ea-9fdc-97fd8f920f91.png)

**Comment by tucan9389** [comment]
Hmm, 🤔 You can make a masked image. (The following step is just to guess, I didn’t try it)

1. Create a mask image with the segmentation map
2. Create a masked image with the original image and mask image (Original image + mask image -> masked image)


The following link would be helped.
https://stackoverflow.com/questions/5757386/how-can-i-mask-a-uiimageview

**Comment by tucan9389** [comment]
@ismailismail 

Did you implement the post-processing? If you can, PR to this repo with new tab bar item!

Thanks
