### ISSUE TITLE
Drawing heatmap view with Metal

### ISSUE THREAD

**Issue by tucan9389** [tucan9389/ObjectSegmentation-CoreML#5]
I'm searching for this issue slowly. https://stackoverflow.com/questions/61154192/are-there-recommended-ways-for-drawing-2d-array-in-fast-time

**Comment by lookdeceline** [comment]
Thanks for the great repo!
Any updates on this issue??

**Comment by tucan9389** [comment]
Here it is! @jsharp83 made the optimized post-process logic using Metal and it's really fast! 
https://github.com/jsharp83/MetalCamera
I plan to adapt it to this repo later.

**Comment by tucan9389** [comment]
## Logic flow of MetalCamera's segmentation example

https://github.com/jsharp83/MetalCamera/blob/master/Example/MetalCamera/SegmentationSampleViewController.swift

<img src="https://user-images.githubusercontent.com/37643248/99236547-aec08980-283a-11eb-9d7b-9c6303ab5187.jpg" width=400px>
