### ISSUE TITLE
Segment whole image

### ISSUE THREAD

**Issue by wuharvey** [tucan9389/ObjectSegmentation-CoreML#6]
Hi there - first off, great work on this repo! :D 

I wonder if there's a way to segment the whole image by padding the sides - as it stands, since `imageCropAndScaleOption` is `.centerCrop`, we only get the center.

**Comment by tucan9389** [comment]
There are three options:
- `.centerCrop`
- `.scaleFit`
- `.scaleFill`

And I think the `.scaleFill` option is that you want.

![image](https://user-images.githubusercontent.com/37643248/97104499-b12a3a80-16f7-11eb-84fd-fd3df40541b6.png)
source: https://developer.apple.com/documentation/vision/vncoremlrequest/2890144-imagecropandscaleoption

**Comment by tucan9389** [comment]
@wuharvey 
If you want to ask more, reopen the issue feel free.
